### ISSUE TITLE
FileNotFoundError: manifest.json

### ISSUE THREAD

**Issue by BaileyTrotter** [roedoejet/mothertongues#12]
I keep running into a "FileNotFoundError: [Errno 2] No such file or directory: 'manifest.json' " error, after line 89 of mtd/parsers/utils.py. 

I'm using the mtd-starter & haven't recieved the "The manifest JSON file at {manifest_path} seems to be malformed. Please run it through a JSON validator" error, so I don't think that's the issue. 

It's probably something on my end but I'm not sure why this is happening!

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - thanks for posting here! Sorry to hear you're having a problem. That "FileNotFoundError" tells me that mothertongues can't find the `manifest.json` file and since the path to that file is configured in your `config.json`, I had a look at your config file: https://github.com/BaileyTrotter/mtd-starter/blob/master/config/config.json 

It looks like your manifest and data files are pointing to not quite the right place. The manifest and resource paths that you define in the config file have to be paths relative to the config file, so `../manifest.json` actually jumps out of [your config directory into the parent directory ](https://stackoverflow.com/questions/23242004/what-is-double-dot-and-single-dot-in-linux) - you want `./manifest.json` instead. Also, your resource declaration there should be `../data/SFN Dictionary.csv`

Let me know if that helps, I'll wait to close this issue until then.

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - where are you seeing this error? It looks like your site has built 
![image](https://user-images.githubusercontent.com/14815080/158854078-355b01ac-02c8-408d-a337-44cdacbb8ad8.png)
and there are no errors. You might need to turn on GitHub Pages before the site will show though.

**Comment by BaileyTrotter** [comment]
@roedoejet I get the error every time in a local clone, so it must be something to do with how the files are stored on my computer. I'll see if I can figure out what's going wrong there. 

I've turned on Github Pages and I see the site shows now, but only with the Danish data. I tried deleting the file with the Danish data in the forked repo and renaming the SFN language data 'data.csv', and now there seems to be an issue with the "pages build and deployment / build (dynamic)" part. 

Thank you for your help so far, and sorry I keep running into more issues each time!

**Comment by roedoejet** [comment]
maybe try using an absolute path instead of a relative one? I will look into this.

Second, you have to edit the `index.html` to point to your js files. You'll notice on lines 20 and 21 they're still pointing to https://roedoejet.github.io/mtd-starter/config-danish.js when they should be pointing to https://BaileyTrotter.github.io/mtd-starter/config-english.js - I guess this is missing in the docs? I'll also look into that

**Comment by BaileyTrotter** [comment]
Thank you! I'll look into your suggestions over the next few days.

**Comment by BaileyTrotter** [comment]
Hi @roedoejet I edited where lines 20 and 21 of the index.html towards. I'm now getting a blank page when I visit the site. Do I need to change anything else in the index.html?

I haven't started working through anything in the "Visualizing your data" portion of the Guides yet, so I haven't changed anything that points towards roedoejet.github.io/mothertongues-UI.

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - can you confirm that you have turned GitHub Pages on and that it's pointing at the right branch? It should look like this:

![image](https://user-images.githubusercontent.com/14815080/159797719-905c76bc-b0ba-4b84-aed4-17f4261d418d.png)

**Comment by BaileyTrotter** [comment]
Oh! That was it, I had it set to Master. Thank you so much. I'll close this issue now.
