### ISSUE TITLE
Committing changes to mothertongues-UI-Web

### ISSUE THREAD

**Issue by BaileyTrotter** [roedoejet/mothertongues#14]
Hi Aidan, 

I am trying to use the mothertongues UI Web interface, and I think everything is working up to the commit stage. The Web UI looks great locally in my browser after I've run `npm start`, but I'm struggling to commit the changes (which is likely from my own inexperience with git!) 

This is the message I've been getting after I run `git commit -a -m 'updated data' && git push origin master`:

<img width="678" alt="Screen Shot 2022-11-25 at 4 20 17 PM" src="https://user-images.githubusercontent.com/96272684/204065919-50ccb38f-cd10-4a64-9fcb-470a7ee2a36c.png">

Do you know if there's a step I've missed somewhere, or something else I need to be doing to get it to publish through GitHub pages?

Thank you!

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - congrats! Everything looks good here, the problem is that I have put a git commit hook on to check that I use something called "conventional commit messages". You can read a bit more about them [here](https://www.conventionalcommits.org/en/v1.0.0/) or [here](https://github.com/conventional-changelog/commitlint/#what-is-commitlint) but basically the problem is with the message "updated data". Instead it would have to be something like `git commit -a -m 'chore: updated data' && git push origin master` the reason for this is because when all of your commits are standardized like this, 1: it makes it harder to write commits that don't hold a lot of information like "changed some stuff" 😄  and 2: there are some benefits for my projects, like the automatic creation of release notes as for example here: https://github.com/roedoejet/g2p/releases/tag/v0.5.20221013 - this whole list of release notes was made possible because of the use of conventional commits. Now, if you want to use them, `git commit -a -m 'chore: updated data' && git push origin master` should suffice as I mentioned, but I encourage you to read the pages about what they are. But, if you don't want to use them, you can add a `-n` to your commit, like `git commit -a -m 'chore: updated data' -n && git push origin master` and that will disable the checking. Have a great weekend and let me know if you still have a problem. If you still have a problem with the UI Web, please raise an issue here: https://github.com/MotherTongues/mothertongues-UI-Web/issues

**Comment by BaileyTrotter** [comment]
Thank you! I'll read up on conventional commit messages to get a better understanding of them.

**Comment by roedoejet** [comment]
Yea! I find them useful but you can safely ignore them with the `-n` flag if you choose 😌😊
